### ISSUE TITLE
Can not install lxml

### ISSUE THREAD

**Issue by Huxpro** [JamesPan/duoshuo-migrator#2]
I search a lot and try a lot....But still failed in `pip install lxml`..

```
error: command 'cc' failed with exit status 1
```
```
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-CsEo6D/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EOxEEu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-CsEo6D/lxml
```

I tried `sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install lxml ` but not works...

**Comment by JamesPan** [comment]
I delete the lxml then reinstall it, fail too...

what a sad story.

OS X 10.11

**Comment by JamesPan** [comment]
@Huxpro 

try `STATIC_DEPS=true pip install lxml`

**Comment by Huxpro** [comment]
@JamesPan 

It works! I remember I tried it..

fine..next question (sigh........):

```
Traceback (most recent call last):
  File "duoshuo-migrator.py", line 144, in <module>
    main()
  File "duoshuo-migrator.py", line 135, in main
    articles = json2objects(data)
  File "duoshuo-migrator.py", line 53, in json2objects
    identifier = art['thread_key']
KeyError: 'thread_key
```

**Comment by Huxpro** [comment]
@JamesPan 

Fine I got it.. I thought I should do some check manually

**Comment by JamesPan** [comment]
#3
