### ISSUE TITLE
一直有报错，有时间帮忙看下吧。

### ISSUE THREAD

**Issue by imbyron** [JamesPan/duoshuo-migrator#5]
python duoshuo-migrator.py -i export.json -o disqus.xml
···
Traceback (most recent call last):
  File "duoshuo-migrator.py", line 148, in <module>
    main()
  File "duoshuo-migrator.py", line 139, in main
    articles = json2objects(data)
  File "duoshuo-migrator.py", line 50, in json2objects
    title = art['title']
KeyError: 'title'
···

**Comment by JamesPan** [comment]
也许是多说又改导出的数据结构了吧。。。如果觉得评论所在文章的title可以不要的话，把第50行改成

```
title=art.get('title', '')
```

，只不过这样不保证导入到disqus后能够正常。

**Comment by imbyron** [comment]
@JamesPan 改成这个也是报错。。。悲了个催的。
