### ISSUE TITLE
转化数据时提示报错，是否目前多说的数据结构有调整呢，麻烦大牛帮帮忙

### ISSUE THREAD

**Issue by wsgzao** [JamesPan/duoshuo-migrator#9]
c:\tmp>python duoshuo-migrator.py -i export.json  -o disqus.xml
Traceback (most recent call last):
  File "duoshuo-migrator.py", line 153, in <module>
    main()
  File "duoshuo-migrator.py", line 145, in main
    result = objects2xml(articles)
  File "duoshuo-migrator.py", line 96, in objects2xml
    print >> sys.stderr, "found article without title, id=%s, link=%s" %(article
.id, article.link)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and
'_io.TextIOWrapper'

**Comment by JamesPan** [comment]
也许你用了python3。本项目不再维护，谨慎使用，自求多福
